/*
 * Symbol for filting coverage results.
 */
#ifndef _FAULT_ROLES_H_
#define _FAULT_ROLES_H_

#define XCOVERAGE
#define _CPP_QUOTE(x) #x
#define STRING_FROM_IDENTIFIER(X) _CPP_QUOTE(X)
#define CONCAT_IDENTIFIER(X, Y) X##Y

#define MODULE_QNAME_STR STRING_FROM_IDENTIFIER(MODULE_QNAME)
#define MODULE_BASENAME_STR STRING_FROM_IDENTIFIER(MODULE_BASENAME)
#define MODULE_PACKAGE_STR STRING_FROM_IDENTIFIER(MODULE_PACKAGE)
#define QPATH(NAME) MODULE_QNAME_STR "." NAME

#define FACTOR_QNAME_STR STRING_FROM_IDENTIFIER(FACTOR_QNAME)
#define FACTOR_BASENAME_STR STRING_FROM_IDENTIFIER(FACTOR_BASENAME)
#define FACTOR_PACKAGE_STR STRING_FROM_IDENTIFIER(FACTOR_PACKAGE)
#define FACTOR_PATH(NAME) FACTOR_QNAME_STR "." NAME

#define F_ROLE_STR STRING_FROM_IDENTIFIER(F_ROLE)
#define F_ROLE_TEST_ID 5
#define F_ROLE_METRICS_ID 10
#define F_ROLE_FACTOR_ID 1
#define F_ROLE_INSPECT_ID -1
#define F_ROLE_DEBUG_ID 2

#define TEST(y) (F_ROLE_ID == F_ROLE_TEST_ID || F_ROLE_ID == F_ROLE_METRICS_ID)
#define DEBUG(y) (F_ROLE_ID == F_ROLE_DEBUG_ID)
#define FACTOR(y) (F_ROLE_ID == F_ROLE_FACTOR_ID)
#define INSPECT(y) (F_ROLE_ID == F_ROLE_INSPECT_ID)
#define METRICS(y) (F_ROLE_ID == F_ROLE_METRICS_ID)

#ifndef F_ROLE_ID
	#error compilation driver was not given a F_ROLE_ID preprocessor definition
#endif

#endif
